### ISSUE TITLE
webstorm里eslint该怎么设置啊，一直报错。

### ISSUE THREAD

**Issue by a347807131** [removeif/hexo-theme-amazing#1]
![image](https://user-images.githubusercontent.com/24996382/76081963-4354c580-5fe5-11ea-8297-3fb3abd515aa.png)
![image](https://user-images.githubusercontent.com/24996382/76082034-667f7500-5fe5-11ea-89b6-a1763f4f4753.png)

**Comment by removeif** [comment]
没用过 webstorm
可以试下 Visual Studio Code 是真香
