### ISSUE TITLE
碎碎念的文字不靠左边

### ISSUE THREAD

**Issue by lsqstudy** [removeif/hexo-theme-amazing#11]
> ## **碎碎念的文字不靠左边**

![image](https://user-images.githubusercontent.com/57124576/78451691-b66f5b80-76b9-11ea-9bf9-bf3edf8afb5f.png)

**Comment by removeif** [comment]
self_talk.md文件中 检查每个html标签是否都是成对的开闭，如有一个<div>就一定要有个</div>

**Comment by lsqstudy** [comment]
没有self_talk.md文件，只有self_talk目录下的index.md文件，而且<div></div>都是成对

**Comment by removeif** [comment]
现在看起来就是不成对导致的,你这样贴出来看下
```html
<div class = "text-center"><h1>碎碎念</h1></div><div class = "text-tips">

tips：github登录后按时间正序查看、可点赞加❤️、本插件[地址](https://github.com/removeif/gitalk)..<span id="busuanzi_container_page_pv">「<span id="busuanzi_value_page_pv">+99</span>次查看」</span></div>
<div id="comment-container1"><div class="text-tips">碎碎念加载中，请稍等...</div></div>
<script>
    $.getScript("/js/gitalk_self.min.js", function () {
        var gitalk = new Gitalk({
            clientID: clientId,
            clientSecret: clientSecret,
            id: '666666',
            repo: 'issue_database',
            owner: 'removeif',
            admin: "removeif",
            createIssueManually: true,
            distractionFreeMode: false
        });
        gitalk.render('comment-container1');
    });
</script>
```

**Comment by lsqstudy** [comment]
<div id="comment-container1"><div class="text-tips">碎碎念加载中，请稍等...</div></div>
<script>
    $.getScript("/js/gitalk_self.min.js", function () {
        var gitalk = new Gitalk({
            clientID: clientId,
            clientSecret: clientSecret,
            id: '666666',
            repo: 'lsqstudy.github.io',
            owner: 'lsqstudy',
            admin: "lsqstudy",
            createIssueManually: true,
            distractionFreeMode: false
        });
        gitalk.render('comment-container1');
    });
</script>

**Comment by lsqstudy** [comment]
```<div id="comment-container1"><div class="text-tips">碎碎念加载中，请稍等...</div></div>
<script>
    $.getScript("/js/gitalk_self.min.js", function () {
        var gitalk = new Gitalk({
            clientID: clientId,
            clientSecret: clientSecret,
            id: '666666',
            repo: 'lsqstudy.github.io',
            owner: 'lsqstudy',
            admin: "lsqstudy",
            createIssueManually: true,
            distractionFreeMode: false
        });
        gitalk.render('comment-container1');
    });
</script>
 ```

**Comment by removeif** [comment]
上面的一起发自我的iPhone------------------ 原始邮件 ------------------发件人: lsqstudy  <notifications@github.com>发送时间: 2020年4月4日 22:16收件人: removeif/hexo-theme-amazing <hexo-theme-amazing@noreply.github.com>抄送: 辣椒の酱 <removeif@163.com>, Comment <comment@noreply.github.com>主题: 回复：[removeif/hexo-theme-amazing] 碎碎念的文字不靠左边 (#11)
<script>
    $.getScript("/js/gitalk_self.min.js", function () {
        var gitalk = new Gitalk({
            clientID: clientId,
            clientSecret: clientSecret,
            id: '666666',
            repo: 'lsqstudy.github.io',
            owner: 'lsqstudy',
            admin: "lsqstudy",
            createIssueManually: true,
            distractionFreeMode: false
        });
        gitalk.render('comment-container1');
    });
</script>


—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/removeif/hexo-theme-amazing/issues/11#issuecomment-609035094",
"url": "https://github.com/removeif/hexo-theme-amazing/issues/11#issuecomment-609035094",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by lsqstudy** [comment]
```java
<div class = "text-center"><h1>碎碎念</h1></div><div class = "text-tips">

tips：github登录后按时间正序查看、可点赞加❤️、本插件[地址](https://github.com/removeif/gitalk)..<span id="busuanzi_container_page_pv">「<span id="busuanzi_value_page_pv">+99</span>次查看」</span></div>
<div id="comment-container1"><div class="text-tips">碎碎念加载中，请稍等...</div></div>
<script>
    $.getScript("/js/gitalk_self.min.js", function () {
        var gitalk = new Gitalk({
            clientID: clientId,
            clientSecret: clientSecret,
            id: '666666',
            repo: 'lsqstudy.github.io',
            owner: 'lsqstudy',
            admin: "lsqstudy",
            createIssueManually: true,
            distractionFreeMode: false
        });
        gitalk.render('comment-container1');
    });
</script>
```

**Comment by lsqstudy** [comment]
谢谢你，已经解决，我直接把这个文件删除了，再下载，然后就解决了。
