### ISSUE TITLE
新建页面可以选择双栏布局吗

### ISSUE THREAD

**Issue by haojie06** [removeif/hexo-theme-amazing#13]
请问hexo new page创建的页面可以选择使用双栏布局吗。

**Comment by removeif** [comment]
现在不就是双栏么，你是说三栏吧，三栏是不行的

**Comment by haojie06** [comment]
好吧，问题解决了。我去看了看默认的确是双栏的，不过这个页面我加了一个layout: true,他就显示成三栏了,一开始我没想到是这个的问题，谢谢了。
