### ISSUE TITLE
一些小问题和小建议

### ISSUE THREAD

**Issue by mocehu** [removeif/hexo-theme-amazing#14]
1.关于手机端关闭看板娘的问题，我之前给您发邮件询问过，在waifu-tips.js文件里，没有直接关闭手机端显示的设置，我想应该是调整这项的参数来达到目的，但是我对高度之类的参数都不熟悉
![image](https://user-images.githubusercontent.com/30388693/79063273-38bbd900-7cd3-11ea-92fe-e3bdb8fb2216.png)
2.gitalk的设置我不是很懂，现在包括我在内的很多人都把博客部署在了coding上面，这样访问起来更快，显然gitalk对于部署在其他仓库的博客就不是那么友好了，经常加载不出来评论的头像，希望可以支持valine评论，主要是热门推荐和最新评论之类的功能要支持

**Comment by removeif** [comment]
1.你就填768px就可以了，一般电脑的笔记本电脑的屏幕是786
2.gitalk 官方有配置说明，或自行百度一下就可以了，在coding上面也可以用。关于valine评论的支持后面会加上
