### ISSUE TITLE
网站尾部的busuanzi统计，咋修改呀...

### ISSUE THREAD

**Issue by a-little-bear** [removeif/hexo-theme-amazing#18]
❤️感谢 99+ 小伙伴的 99+ 次光临！❤️

上面这是我博客的统计，有没有啥办法给出准确数字呢。。

我尝试看大佬们issue啥的，好像是在/layout/common/footer,jsx修改的？
`visitorCounterTitle: _p('plugin.footer_visitor', '<span id="busuanzi_value_site_uv">99+</span>', '<span id="busuanzi_value_site_pv">99+</span>'),`
是这段代码吗？我看有99+的字样。。
小白小白，希望大佬能给个方法，感激不尽....

**Comment by removeif** [comment]
> ❤️感谢 99+ 小伙伴的 99+ 次光临！❤️
> 
> 上面这是我博客的统计，有没有啥办法给出准确数字呢。。
> 
> 我尝试看大佬们issue啥的，好像是在/layout/common/footer,jsx修改的？
> `visitorCounterTitle: _p('plugin.footer_visitor', '<span id="busuanzi_value_site_uv">99+</span>', '<span id="busuanzi_value_site_pv">99+</span>'),`
> 是这段代码吗？我看有99+的字样。。
> 小白小白，希望大佬能给个方法，感激不尽....

不用修改，会自己填充真实的访问数据，你看下是不是哪里报错了，可以把网站部署了贴出来，方便查看

**Comment by a-little-bear** [comment]
> > ❤️感谢 99+ 小伙伴的 99+ 次光临！❤️
> > 上面这是我博客的统计，有没有啥办法给出准确数字呢。。
> > 我尝试看大佬们issue啥的，好像是在/layout/common/footer,jsx修改的？
> > `visitorCounterTitle: _p('plugin.footer_visitor', '<span id="busuanzi_value_site_uv">99+</span>', '<span id="busuanzi_value_site_pv">99+</span>'),`
> > 是这段代码吗？我看有99+的字样。。
> > 小白小白，希望大佬能给个方法，感激不尽....
> 
> 不用修改，会自己填充真实的访问数据，你看下是不是哪里报错了，可以把网站部署了贴出来，方便查看

http://www.alittlebear.tk/
https://github.com/a-little-bear/a-little-bear.github.io
真的很抱歉呀大大。。

**Comment by a-little-bear** [comment]
> > ❤️感谢 99+ 小伙伴的 99+ 次光临！❤️
> > 上面这是我博客的统计，有没有啥办法给出准确数字呢。。
> > 我尝试看大佬们issue啥的，好像是在/layout/common/footer,jsx修改的？
> > `visitorCounterTitle: _p('plugin.footer_visitor', '<span id="busuanzi_value_site_uv">99+</span>', '<span id="busuanzi_value_site_pv">99+</span>'),`
> > 是这段代码吗？我看有99+的字样。。
> > 小白小白，希望大佬能给个方法，感激不尽....
> 
> 不用修改，会自己填充真实的访问数据，你看下是不是哪里报错了，可以把网站部署了贴出来，方便查看

哇塞，真的抱歉大大，不知道为啥，搞了半天的东西都自己好了。。
那个busuanzi是，另外一个加密文章也是。。我这博客真奇怪
