### ISSUE TITLE
自定义widget

### ISSUE THREAD

**Issue by MaiIDesign** [removeif/hexo-theme-amazing#19]
嗨，我想了解下怎么增加自定义的widget，比如在右侧做一个网站的公告栏，显示一些信息，这个该如何处理？

**Comment by removeif** [comment]
> 嗨，我想了解下怎么增加自定义的widget，比如在右侧做一个网站的公告栏，显示一些信息，这个该如何处理？

稍等，我这两天空了写个教程，还是有点复杂的，一两句说不清

**Comment by removeif** [comment]
> 嗨，我想了解下怎么增加自定义的widget，比如在右侧做一个网站的公告栏，显示一些信息，这个该如何处理？

参考这个[issue链接](https://github.com/removeif/hexo-theme-amazing/issues/16#issuecomment-632595739)

**Comment by MaiIDesign** [comment]
晓得，非常感谢
