### ISSUE TITLE
菜单栏，选中时菜单的颜色不会取消

### ISSUE THREAD

**Issue by dream-kzx** [removeif/hexo-theme-amazing#20]
![image](https://user-images.githubusercontent.com/37357956/83970001-af590980-a905-11ea-9254-25f371d0b04e.png)
        我看了博主的源码，发现没有实现，对于菜单的颜色选择是使用stylue语法实现的，但focus不在菜单时，选中菜单的颜色就会消失。
       因为很少接触前端，我自己改不了代码，希望博主能修复一下

**Comment by removeif** [comment]
> ![image](https://user-images.githubusercontent.com/37357956/83970001-af590980-a905-11ea-9254-25f371d0b04e.png)
> 我看了博主的源码，发现没有实现，对于菜单的颜色选择是使用stylue语法实现的，但focus不在菜单时，选中菜单的颜色就会消失。
> 因为很少接触前端，我自己改不了代码，希望博主能修复一下

确实有这个问题存在，但是是因为 pjax的原因，pjax 局部刷新没刷新菜单栏，所以颜色不会改变，回头有时间看下怎么调整一下
