### ISSUE TITLE
生成的index.html文件为空白

### ISSUE THREAD

**Issue by suoga1406886** [removeif/hexo-theme-amazing#21]
[log.txt](https://github.com/removeif/hexo-theme-amazing/files/4788570/log.txt)
18:32:38.174 ERROR Process failed: _posts/杩欐槸绗竴涓?md
YAMLException: end of the stream or a document separator is expected at line 1, column 1:
应该是这个错误，但是我不知道怎么改。。。。

**Comment by removeif** [comment]
> [log.txt](https://github.com/removeif/hexo-theme-amazing/files/4788570/log.txt)
> 18:32:38.174 ERROR Process failed: _posts/杩欐槸绗竴涓?md
> YAMLException: end of the stream or a document separator is expected at line 1, column 1:
> 应该是这个错误，但是我不知道怎么改。。。。

主题的配置文件 _config贴出来看下

**Comment by suoga1406886** [comment]
[_config.txt](https://github.com/removeif/hexo-theme-amazing/files/4789998/_config.txt)
其实还没有改什么，麻烦了

**Comment by suoga1406886** [comment]
> > [log.txt](https://github.com/removeif/hexo-theme-amazing/files/4788570/log.txt)
> > 18:32:38.174 ERROR Process failed: _posts/杩欐槸绗竴涓?md
> > YAMLException: end of the stream or a document separator is expected at line 1, column 1:
> > 应该是这个错误，但是我不知道怎么改。。。。
> 
> 主题的配置文件 _config贴出来看下

[_config.txt](https://github.com/removeif/hexo-theme-amazing/files/4790018/_config.txt)
其实并没有改太多，麻烦了

**Comment by removeif** [comment]
> > > [log.txt](https://github.com/removeif/hexo-theme-amazing/files/4788570/log.txt)
> > > 18:32:38.174 ERROR Process failed: _posts/杩欐槸绗竴涓?md
> > > YAMLException: end of the stream or a document separator is expected at line 1, column 1:
> > > 应该是这个错误，但是我不知道怎么改。。。。
> > 
> > 
> > 主题的配置文件 _config贴出来看下
> 
> [_config.txt](https://github.com/removeif/hexo-theme-amazing/files/4790018/_config.txt)
> 其实并没有改太多，麻烦了

之前配置文件中少注释了一个-，已经注释上了，你重新pull 一下代码就好

**Comment by suoga1406886** [comment]
> > > > [log.txt](https://github.com/removeif/hexo-theme-amazing/files/4788570/log.txt)
> > > > 18:32:38.174 ERROR Process failed: _posts/杩欐槸绗竴涓?md
> > > > YAMLException: end of the stream or a document separator is expected at line 1, column 1:
> > > > 应该是这个错误，但是我不知道怎么改。。。。
> > > 
> > > 
> > > 主题的配置文件 _config贴出来看下
> > 
> > 
> > [_config.txt](https://github.com/removeif/hexo-theme-amazing/files/4790018/_config.txt)
> > 其实并没有改太多，麻烦了
> 
> 之前配置文件中少注释了一个-，已经注释上了，你重新pull 一下代码就好

好的，十分感谢！
