### ISSUE TITLE
考虑内嵌404页面吗

### ISSUE THREAD

**Issue by wsdydeni** [removeif/hexo-theme-amazing#24]
找到了很好看的404页面 不知道怎么加

**Comment by removeif** [comment]
> 找到了很好看的404页面 不知道怎么加

有时间的时候加进去

**Comment by wsdydeni** [comment]
@removeif 大佬 首页最新评论用了哪些文件呀 可以告诉一下小白我吗？ 我自己抽出来加就行

**Comment by removeif** [comment]
> @removeif 大佬 首页最新评论用了哪些文件呀 可以告诉一下小白我吗？ 我自己抽出来加就行

主要是这个[文件](https://github.com/removeif/hexo-theme-amazing/blob/6e32e7dbb984192b231e79c27d30efc2fe265e7a/source/js/comment-issue-data.js#L260)
以及这里是入口
最新评论跟这个404页面有啥关系？

**Comment by wsdydeni** [comment]
@removeif  哈哈哈~ 404页面我自己加了 这个是我的博客https://www.wsdydeni.top/ 大佬过过眼

**Comment by removeif** [comment]
> @removeif 哈哈哈~ 404页面我自己加了 这个是我的博客https://www.wsdydeni.top/ 大佬过过眼

可以，弄得不错👍
