### ISSUE TITLE
进入文章后右边不显示文章目录

### ISSUE THREAD

**Issue by zzdespair** [removeif/hexo-theme-amazing#25]
再点击进入文章后，右边文章的目录不显示，还是只显示个人介绍，请问是需要配置什么，还是说我的文章有问题所以无法生成目录吗？

**Comment by removeif** [comment]
> 再点击进入文章后，右边文章的目录不显示，还是只显示个人介绍，请问是需要配置什么，还是说我的文章有问题所以无法生成目录吗？

头部要打开toc,最好把网址贴出来
