### ISSUE TITLE
busuanzi的单篇文章阅读统计有问题

### ISSUE THREAD

**Issue by cooper-q** [removeif/hexo-theme-amazing#27]
>以前用的leancloud进行单篇文章统计，最近不实名认证不给用，换成busuanzi后发现单篇文章的统计貌似是有问题。
>每次进入首页后再点击进入一篇文章后会+3，刷新单篇文章则+1，同样如果退出到首页后点击另一篇也是这样。
>但是他们会以同一个基数进行增加，这样会导致每篇文章的阅读次数几乎相近。感觉不像是对每一篇文章进行单独计算统计。

- 文章1

![image](https://user-images.githubusercontent.com/19221882/92550910-4d56ca00-f28f-11ea-80e7-552cc4fb2361.png)

- 文章2

![image](https://user-images.githubusercontent.com/19221882/92550912-4e87f700-f28f-11ea-9ebb-7a112fd7307b.png)

**Comment by removeif** [comment]
> > 以前用的leancloud进行单篇文章统计，最近不实名认证不给用，换成busuanzi后发现单篇文章的统计貌似是有问题。
> > 每次进入首页后再点击进入一篇文章后会+3，刷新单篇文章则+1，同样如果退出到首页后点击另一篇也是这样。
> > 但是他们会以同一个基数进行增加，这样会导致每篇文章的阅读次数几乎相近。感觉不像是对每一篇文章进行单独计算统计。
> 
> * 文章1
> 
> ![image](https://user-images.githubusercontent.com/19221882/92550910-4d56ca00-f28f-11ea-80e7-552cc4fb2361.png)
> 
> * 文章2
> 
> ![image](https://user-images.githubusercontent.com/19221882/92550912-4e87f700-f28f-11ea-9ebb-7a112fd7307b.png)

已发现问题，最近排查修复

**Comment by removeif** [comment]
> > 以前用的leancloud进行单篇文章统计，最近不实名认证不给用，换成busuanzi后发现单篇文章的统计貌似是有问题。
> > 每次进入首页后再点击进入一篇文章后会+3，刷新单篇文章则+1，同样如果退出到首页后点击另一篇也是这样。
> > 但是他们会以同一个基数进行增加，这样会导致每篇文章的阅读次数几乎相近。感觉不像是对每一篇文章进行单独计算统计。
> 
> * 文章
> 
> ![image](https://user-images.githubusercontent.com/19221882/92550910-4d56ca00-f28f-11ea-80e7-552cc4fb2361.png)
> 
> * 文章2
> 
> ![image](https://user-images.githubusercontent.com/19221882/92550912-4e87f700-f28f-11ea-9ebb-7a112fd7307b.png)

这个是浏览器的问题，最新版本的Chrome上传的reference 就是 域名，没加具体路径和 Safari浏览器一样，Firefox就没问题
