### ISSUE TITLE
页面缩小之后，底部栏飘上来了

### ISSUE THREAD

**Issue by cjliux** [removeif/hexo-theme-amazing#28]
页面缩小之后，底部栏飘上来了

**Comment by removeif** [comment]
> 页面缩小之后，底部栏飘上来了

是怎么缩小的方式呢，直接ctr+ - 吗，还是适应移动端缩小？我这边没发现问题

**Comment by cjliux** [comment]
是的，chrome中缩放80%以上时，底部栏会悬空

**Comment by removeif** [comment]
> 是的，chrome中缩放80%以上时，底部栏会悬空

能截个图不，我这边没发现哦
![image](https://user-images.githubusercontent.com/10427139/93564059-a7583d80-f9bb-11ea-8f13-c9832d51b703.png)

**Comment by cjliux** [comment]
![屏幕截图 2020-09-18 143607](https://user-images.githubusercontent.com/14961563/93564592-85ab8600-f9bc-11ea-959b-cccf443a65af.png)

**Comment by removeif** [comment]
@cjliux 你的内容太少了，有一页内容的时候就不会出现了

**Comment by cjliux** [comment]
okk
