### ISSUE TITLE
bug 当post设置了author值后，footer中的就变成了post的author值，而非站点author值。

### ISSUE THREAD

**Issue by a347807131** [removeif/hexo-theme-amazing#3]
![image](https://user-images.githubusercontent.com/24996382/76142879-d3aa0d80-60ac-11ea-9aae-aacaf200693e.png)

**Comment by removeif** [comment]
我看取的是 博客配置文件中的
![](https://cdn.jsdelivr.net/gh/removeif/blog_image/img/2020/20200307200534.png)

**Comment by a347807131** [comment]
@removeif 
![image](https://user-images.githubusercontent.com/24996382/76143134-8f6c3c80-60af-11ea-8b19-853315c3f7ae.png)
好像是先去author值，为空则取siteTitle

**Comment by removeif** [comment]
> @removeif
> ![image](https://user-images.githubusercontent.com/24996382/76143134-8f6c3c80-60af-11ea-8b19-853315c3f7ae.png)
> 好像是先去author值，为空则取siteTitle。而这里author取了post.author的值。
> 正常逻辑不该是，先取站点author的值，为空则取site,title的值吗？
> 
> 例如，我站点author为`Gatsby`，转载的文章post.author的值是原作者`白头豕 `。
> post-copyright的值就是这样没问题。
> ![image](https://user-images.githubusercontent.com/24996382/76143208-65ffe080-60b0-11ea-858f-b228d6df903d.png)
> 但，该post页的footer也成了`白头豕 `。
> ![image](https://user-images.githubusercontent.com/24996382/76143255-b9722e80-60b0-11ea-84b9-e6bd57ad0d89.png)
> 
> 难道应该是这样吗？
> `

我看了这问题，因为原主题作者应该没考虑到这个问题，渲染的时候把post头部一起加入到了config中，同时覆写了配置中同名的属性，可以给重新命名一下，post文章头部中填post_author,同时article 中作者也取这个，你有空可以试下
```html
                        <li><strong>本文作者：</strong><a href={url_for(config.url)}>{page.post_author|config.author}</a></li>
```
