### ISSUE TITLE
百度和谷歌的数据统计问题

### ISSUE THREAD

**Issue by feiyuggg** [removeif/hexo-theme-amazing#30]
想请教一下如何开启百度或者谷歌的统计，需要修改js的哪些地方，谢谢

**Comment by removeif** [comment]
> 想请教一下如何开启百度或者谷歌的统计，需要修改js的哪些地方，谢谢

申请好相应的id 填到主题配置文件中就可以了
![image](https://user-images.githubusercontent.com/10427139/98459526-974c2580-21d6-11eb-80aa-d4a3d6cf369d.png)

**Comment by feiyuggg** [comment]
![image](https://user-images.githubusercontent.com/43964724/98459641-b4cdbf00-21d7-11eb-928a-524caf5443c0.png)
代码块变成这样了，执行不了

**Comment by removeif** [comment]
> ![image](https://user-images.githubusercontent.com/43964724/98459641-b4cdbf00-21d7-11eb-928a-524caf5443c0.png)
> 代码块变成这样了，执行不了

我这边配置了没问题，只是加了这个两个id 就执行不了吗？不会吧

**Comment by feiyuggg** [comment]
已经解决，非常感谢 orz
