### ISSUE TITLE
关于jsdelivr的一点小问题

### ISSUE THREAD

**Issue by haojie06** [removeif/hexo-theme-amazing#4]
我在配置文件
![image](https://user-images.githubusercontent.com/32638818/76546563-b4edb180-64c6-11ea-837e-6e693e28d161.png)l里面这样填写了jsdelivr的url，但是我发现生成的网页中调用的部分js(如main.js insight.js等等)还是直接通过github来获取的，国内一些地方访问github的资源相当的慢，请问这里是我配置文件写错了吗？还是就是这样的？

**Comment by removeif** [comment]
> 我在配置文件
> ![image](https://user-images.githubusercontent.com/32638818/76546563-b4edb180-64c6-11ea-837e-6e693e28d161.png)l里面这样填写了jsdelivr的url，但是我发现生成的网页中调用的部分js(如main.js insight.js等等)还是直接通过github来获取的，国内一些地方访问github的资源相当的慢，请问这里是我配置文件写错了吗？还是就是这样的？

这个配置暂时还没有做进去，暂时不能生效，相当于没用

**Comment by removeif** [comment]
> 我在配置文件
> ![image](https://user-images.githubusercontent.com/32638818/76546563-b4edb180-64c6-11ea-837e-6e693e28d161.png)l里面这样填写了jsdelivr的url，但是我发现生成的网页中调用的部分js(如main.js insight.js等等)还是直接通过github来获取的，国内一些地方访问github的资源相当的慢，请问这里是我配置文件写错了吗？还是就是这样的？

最新代码已生效！

**Comment by haojie06** [comment]
辛苦了👍
