### ISSUE TITLE
关于toc的一点小建议

### ISSUE THREAD

**Issue by haojie06** [removeif/hexo-theme-amazing#5]
个人觉得目前的toc栏显示的东西还是少了，一级标题不是特别有必要显示在里面，而实际能用得到的就剩下二级和三级标题了，如果博客四级/五级标题较多的话阅读起来还是有一些不方便，如果能变成阅读滚动到一个大标题所在的地方时展开显示更多的小标题感觉会更加好一些。

**Comment by removeif** [comment]
嗯，这个看后面有时间了去弄

**Comment by removeif** [comment]
已解决此问题！

**Comment by haojie06** [comment]
您好，更新后toc折叠是生效了，但是我这遇到了一个问题，在已经设置了左侧边栏sticky: true的情况下，向下滚动的时文章还没看完，左侧的目录栏就已经滚动出去了。 https://notesail.com/posts/chevereto-imgs.html 可以看看这个网页

**Comment by removeif** [comment]
> 您好，更新后toc折叠是生效了，但是我这遇到了一个问题，在已经设置了左侧边栏sticky: true的情况下，向下滚动的时文章还没看完，左侧的目录栏就已经滚动出去了。 https://notesail.com/posts/chevereto-imgs.html 可以看看这个网页

这个解决不了，sticky固定后会算总高度，使之整体对齐。

**Comment by haojie06** [comment]
好吧，那大概是我左边放的东西太多了

**Comment by kaiattrib** [comment]
@removeif Hello，作者你好，请教一下，我用了最新的hexo-theme-icarus master代码。改用 你修改的 toc 文件，想实现和你博客中一样的效果，解决目录过长的，实现目录折叠的问题。hexo g 成功了，但是实际没有生效，可以请教一下我漏掉什么了吗？ [https://github.com/removeif/hexo-theme-amazing/blob/master/layout/widget/toc.jsx](https://github.com/removeif/hexo-theme-amazing/blob/master/layout/widget/toc.jsx)

**Comment by removeif** [comment]
> @removeif Hello，作者你好，请教一下，我用了最新的hexo-theme-icarus master代码。改用 你修改的 toc 文件，想实现和你博客中一样的效果，解决目录过长的，实现目录折叠的问题。hexo g 成功了，但是实际没有生效，可以请教一下我漏掉什么了吗？ https://github.com/removeif/hexo-theme-amazing/blob/master/layout/widget/toc.jsx

源码里toc.js一起复制过去
