### ISSUE TITLE
api.github.com/user 401

### ISSUE THREAD

**Issue by qmy777** [removeif/hexo-theme-amazing#7]
想问下
我这边配置gitalk  api.github.io/user 401  是什么情况呢？

**Comment by removeif** [comment]
参考gitalk 这个 [issue](https://github.com/gitalk/gitalk/issues/183)

**Comment by qmy777** [comment]
感谢  昨天被我折腾出来了  发现好像hexo的缓存很严重（不知道是hexo还是主题的，还没有验证过）
