### ISSUE TITLE
灯箱图片在手机上无法缩放

### ISSUE THREAD

**Issue by haojie06** [removeif/hexo-theme-amazing#8]
手机上访问该主题的网站，在需要看一些图片时感觉图片很小，点击图片进入灯箱模式后图片依旧很小，而手机上的chrome是没办法直接放大网页的，感觉当前使用的灯箱js缺少了缩放的功能有一些不方便。希望作者能够完善一下，我觉得[matery](https://blinkfox.github.io/2018/09/28/qian-duan/hexo-bo-ke-zhu-ti-zhi-hexo-theme-matery-de-jie-shao/)主题使用的这个灯箱js效果就很好，可以参考一下。

**Comment by removeif** [comment]
已添加配置，修复

**Comment by haojie06** [comment]
好的，谢谢大佬，期待主题更加完善
