### ISSUE TITLE
有些英语无法变中文

### ISSUE THREAD

**Issue by lsqstudy** [removeif/hexo-theme-amazing#9]
文章中的日期在哪里设置成中文？
![bb](https://user-images.githubusercontent.com/57124576/78337724-02d86f80-75c4-11ea-9f20-d66203b147b9.png)
归档在哪里设置成中文？
![cc](https://user-images.githubusercontent.com/57124576/78337731-07048d00-75c4-11ea-888d-0836200470ef.png)

**Comment by removeif** [comment]
博客配置文件_config.yml中，设置language: zh-CN

**Comment by lsqstudy** [comment]
感谢大神
